"""username and password

Revision ID: 48cdcb5f5c01
Revises: e1f0070edf12
Create Date: 2018-03-19 15:14:57.856109

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '48cdcb5f5c01'
down_revision = 'e1f0070edf12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('username', sa.Text(), nullable=True))
    op.create_unique_constraint(None, 'users', ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'username')
    op.drop_column('users', 'password')
    # ### end Alembic commands ###
