"""adding password and username

Revision ID: 23845c0aae44
Revises: 22719a97ab75
Create Date: 2018-03-19 15:51:19.755497

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23845c0aae44'
down_revision = '22719a97ab75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.Text(), nullable=False))
    op.add_column('users', sa.Column('username', sa.Text(), nullable=False))
    op.alter_column('users', 'first_name',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('users', 'last_name',
               existing_type=sa.TEXT(),
               nullable=False)
    op.create_unique_constraint(None, 'users', ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.alter_column('users', 'last_name',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('users', 'first_name',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_column('users', 'username')
    op.drop_column('users', 'password')
    # ### end Alembic commands ###
