"""empty message

Revision ID: 306150d83526
Revises: ffcfb47bdb84
Create Date: 2018-03-13 18:28:44.031826

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '306150d83526'
down_revision = 'ffcfb47bdb84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages', sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('content', sa.Text(), nullable=True),
                    sa.Column('user_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(
                        ['user_id'],
                        ['users.id'],
                    ), sa.PrimaryKeyConstraint('id'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('messages')
    # ### end Alembic commands ###
