"""added a username column to users

Revision ID: 54903d8da9a0
Revises: fe55ef5635ab
Create Date: 2018-03-19 18:52:51.839258

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54903d8da9a0'
down_revision = 'fe55ef5635ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.Text(), nullable=False))
    op.drop_constraint('users_last_name_key', 'users', type_='unique')
    op.create_unique_constraint(None, 'users', ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.create_unique_constraint('users_last_name_key', 'users', ['last_name'])
    op.drop_column('users', 'username')
    # ### end Alembic commands ###
