"""add foreign_key with messages

Revision ID: 6a7c04785f2f
Revises: a7c7f1b46613
Create Date: 2018-03-14 14:57:47.804388

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a7c04785f2f'
down_revision = 'a7c7f1b46613'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('message_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'messages', 'users', ['message_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_column('messages', 'message_id')
    # ### end Alembic commands ###
