"""added password with bcrypt verification

Revision ID: 7174b91e02c6
Revises: f7d5c9451cc3
Create Date: 2018-03-19 15:08:57.945178

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7174b91e02c6'
down_revision = 'f7d5c9451cc3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password')
    # ### end Alembic commands ###
