"""added unique constraint to last_name

Revision ID: fe55ef5635ab
Revises: 7174b91e02c6
Create Date: 2018-03-19 16:17:47.439964

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe55ef5635ab'
down_revision = '7174b91e02c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'first_name',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('users', 'last_name',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('users', 'password',
               existing_type=sa.TEXT(),
               nullable=False)
    op.create_unique_constraint(None, 'users', ['last_name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.alter_column('users', 'password',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('users', 'last_name',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('users', 'first_name',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###
