"""adding prettiness

Revision ID: 044a118a99cb
Revises: 9edf4913123f
Create Date: 2018-03-14 14:21:42.527910

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '044a118a99cb'
down_revision = '9edf4913123f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sunsets', sa.Column('prettiness', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sunsets', 'prettiness')
    # ### end Alembic commands ###
