"""url not nullable

Revision ID: 0789e3cd1cb9
Revises: a3d022eaa646
Create Date: 2018-03-12 17:09:09.816086

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '0789e3cd1cb9'
down_revision = 'a3d022eaa646'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'sunsets', 'image_url', existing_type=sa.TEXT(), nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'sunsets', 'image_url', existing_type=sa.TEXT(), nullable=True)
    # ### end Alembic commands ###
