"""making image url nullable - false

Revision ID: 080cc8b48c73
Revises: 044a118a99cb
Create Date: 2018-03-14 14:25:50.214904

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '080cc8b48c73'
down_revision = '044a118a99cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sunsets', 'image_url',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sunsets', 'image_url',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###
