"""change beauty to Integer from text

Revision ID: 1138455c0591
Revises: e855e0b420d6
Create Date: 2018-03-12 19:34:19.799801

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1138455c0591'
down_revision = 'e855e0b420d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
   op.alter_column('sunsets', 'beauty', type_=sa.Integer(), postgresql_using='beauty::integer')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sunsets', 'beauty', type_=sa.Text(), postgresql_using='beauty::text')
    # ### end Alembic commands ###
