"""adding img_url and caption columns

Revision ID: 11a102988ccb
Revises: fba4ffd7b233
Create Date: 2018-03-12 14:00:55.680542

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11a102988ccb'
down_revision = 'fba4ffd7b233'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pizza', sa.Column('caption', sa.Text(), nullable=True))
    op.add_column('pizza', sa.Column('img_url', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pizza', 'img_url')
    op.drop_column('pizza', 'caption')
    # ### end Alembic commands ###
