"""added sunset location column

Revision ID: 168eadf771c5
Revises: 4a59fed5a5d6
Create Date: 2018-03-12 13:47:54.517098

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '168eadf771c5'
down_revision = '4a59fed5a5d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sunsets', sa.Column('location', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sunsets', 'location')
    # ### end Alembic commands ###
