"""beauty data change from string to int

Revision ID: 1ba3efec1f08
Revises: 9db8bcff1d34
Create Date: 2018-03-12 17:51:27.077315

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '1ba3efec1f08'
down_revision = '9db8bcff1d34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'sunsets',
        'beauty',
        existing_type=sa.TEXT(),
        type_=sa.Integer(),
        existing_nullable=True,
        postgresql_using="beauty::integer")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'sunsets',
        'beauty',
        existing_type=sa.Integer(),
        type_=sa.TEXT(),
        existing_nullable=True)
    # ### end Alembic commands ###
