"""try to change to int

Revision ID: 1e538908165e
Revises: 99aac9513aa9
Create Date: 2018-03-12 17:00:53.687461

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '1e538908165e'
down_revision = '99aac9513aa9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'meats',
        'umaminess',
        existing_type=sa.TEXT(),
        type_=sa.Integer(),
        postgresql_using="umaminess::integer",
        existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'meats',
        'umaminess',
        existing_type=sa.Integer(),
        type_=sa.TEXT(),
        existing_nullable=True)
    # ### end Alembic commands ###
