"""adding location field to db

Revision ID: 204586704dff
Revises: 401cabb62aa2
Create Date: 2018-03-12 18:18:35.724024

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '204586704dff'
down_revision = '401cabb62aa2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sunsets', sa.Column('location', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sunsets', 'location')
    # ### end Alembic commands ###
