"""creation

Revision ID: 2475943f2b73
Revises:
Create Date: 2018-03-12 14:00:25.324918

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '2475943f2b73'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sunsets', sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('url', sa.Text(), nullable=True),
                    sa.Column('caption', sa.Text(), nullable=True),
                    sa.PrimaryKeyConstraint('id'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sunsets')
    # ### end Alembic commands ###
