"""change type to integer

Revision ID: 34daae8d64a2
Revises: bc8d7bad38b0
Create Date: 2018-03-12 16:54:46.606668

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34daae8d64a2'
down_revision = 'bc8d7bad38b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sunsets', 'beauty',
               existing_type=sa.TEXT(),
               type_=sa.Integer(),
               postgresql_using='beauty::integer',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sunsets', 'beauty',
               existing_type=sa.Integer(),
               type_=sa.TEXT(),
               existing_nullable=True)
    # ### end Alembic commands ###
