"""add prettiness

Revision ID: 35a7679f795c
Revises: 2246b0cf66be
Create Date: 2018-03-12 19:31:37.306795

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35a7679f795c'
down_revision = '2246b0cf66be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sunsets', sa.Column('prettiness', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sunsets', 'prettiness')
    # ### end Alembic commands ###
