"""changed column named \'prettiness\' to \'beauty\'

Revision ID: 3a5e5c8411c7
Revises: 65dcfd23fa81
Create Date: 2018-03-12 14:23:27.955157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a5e5c8411c7'
down_revision = '65dcfd23fa81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sunsets', sa.Column('beauty', sa.Integer(), nullable=True))
    op.drop_column('sunsets', 'prettiness')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sunsets', sa.Column('prettiness', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('sunsets', 'beauty')
    # ### end Alembic commands ###
