"""first version

Revision ID: 415b345e6e3c
Revises: 
Create Date: 2018-03-12 16:57:07.791299

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '415b345e6e3c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sunsets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('img_url', sa.Text(), nullable=True),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sunsets')
    # ### end Alembic commands ###
