"""making url to not null

Revision ID: 49ff08e0e652
Revises: 8ed12ae8043f
Create Date: 2018-03-12 18:38:23.461987

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49ff08e0e652'
down_revision = '8ed12ae8043f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sunsets', 'img_url',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sunsets', 'img_url',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###
