"""changing prettiness to beauty

Revision ID: 60e4b8c0d1c1
Revises: 080cc8b48c73
Create Date: 2018-03-14 14:28:39.236351

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60e4b8c0d1c1'
down_revision = '080cc8b48c73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sunsets', sa.Column('beauty', sa.Text(), nullable=True))
    op.drop_column('sunsets', 'prettiness')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sunsets', sa.Column('prettiness', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('sunsets', 'beauty')
    # ### end Alembic commands ###
