"""change img_url to not nullable

Revision ID: 644add8be9bd
Revises: 775f126f2850
Create Date: 2018-03-12 18:38:21.132849

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '644add8be9bd'
down_revision = '775f126f2850'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sunsets', 'img_url',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sunsets', 'img_url',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###
