"""adding url, caption column

Revision ID: 6c93d8c78c6d
Revises: b90d0880e16b
Create Date: 2018-03-12 14:01:13.995995

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c93d8c78c6d'
down_revision = 'b90d0880e16b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sunsets', sa.Column('caption', sa.Text(), nullable=True))
    op.add_column('sunsets', sa.Column('img_url', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sunsets', 'img_url')
    op.drop_column('sunsets', 'caption')
    # ### end Alembic commands ###
