"""added prettiness column

Revision ID: 6ffd8a80b671
Revises: 168eadf771c5
Create Date: 2018-03-12 14:12:18.025908

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ffd8a80b671'
down_revision = '168eadf771c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sunsets', sa.Column('prettiness', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sunsets', 'prettiness')
    # ### end Alembic commands ###
