"""prettiness column null=False

Revision ID: 712bc7fe4cb7
Revises: 923ef7043af6
Create Date: 2018-03-12 16:25:49.217380

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '712bc7fe4cb7'
down_revision = '923ef7043af6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sunsets', 'url', existing_type=sa.TEXT(), nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sunsets', 'url', existing_type=sa.TEXT(), nullable=True)
    # ### end Alembic commands ###
