"""added prettiness

Revision ID: 775f126f2850
Revises: f516c94e8a84
Create Date: 2018-03-12 18:30:31.182539

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '775f126f2850'
down_revision = 'f516c94e8a84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sunsets', sa.Column('prettiness', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sunsets', 'prettiness')
    # ### end Alembic commands ###
