"""this is hopefully the last time two values initialise

Revision ID: 7fec20ad9aa8
Revises: 
Create Date: 2018-03-12 17:03:30.556283

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7fec20ad9aa8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sunsets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('img_url', sa.Text(), nullable=True),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sunsets')
    # ### end Alembic commands ###
