"""change prettiness to beauty

Revision ID: 870bb612e7fd
Revises: bc4ba8a6b6da
Create Date: 2018-03-12 20:32:30.550709

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '870bb612e7fd'
down_revision = 'bc4ba8a6b6da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sunsets', sa.Column('beauty', sa.Text(), nullable=True))
    op.drop_column('sunsets', 'prettiness')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sunsets', sa.Column('prettiness', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('sunsets', 'beauty')
    # ### end Alembic commands ###
