"""beauty changed to int

Revision ID: 902c86731fbb
Revises: 870bb612e7fd
Create Date: 2018-03-12 21:17:39.003237

"""
from alembic import op
import sqlalchemy as sa

# http://alembic.zzzcomputing.com/en/latest/ops.html#alembic.operations.Operations.alter_column.params.postgresql_using
# from alembic.migration import MigrationContext
# from alembic.operations import Operations

# conn = myengine.connect()
# ctx = MigrationContext.configure(conn)
# op = Operations(ctx)

# op.alter_column("t", "c", nullable=True)

# revision identifiers, used by Alembic.
revision = '902c86731fbb'
down_revision = '870bb612e7fd'
branch_labels = None
depends_on = None

op.alter_column("t", "c", nullable=True)


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sunsets', 'beauty',
                    existing_type=sa.TEXT(),
                    type_=sa.Integer(),
                    existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sunsets', 'beauty',
                    existing_type=sa.Integer(),
                    type_=sa.TEXT(),
                    existing_nullable=True)
    # ### end Alembic commands ###
