"""changing prettiness to beauty

Revision ID: 90d6930e06fd
Revises: a9abb6d5b8e8
Create Date: 2018-03-12 19:16:41.606797

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90d6930e06fd'
down_revision = 'a9abb6d5b8e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('sunsets', sa.Column('beauty', sa.Text(), nullable=True))
    # op.drop_column('sunsets', 'prettiness')
    op.alter_column('sunsets', 'prettiness', new_column_name='beauty')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('sunsets', sa.Column('prettiness', sa.TEXT(), autoincrement=False, nullable=True))
    # op.drop_column('sunsets', 'beauty')
    op.alter_column('sunsets', 'beauty', new_column_name='prettiness')
    # ### end Alembic commands ###
