"""location added to model

Revision ID: 97c2f2e92359
Revises: 2260b7ce0a62
Create Date: 2018-03-12 14:47:04.693512

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97c2f2e92359'
down_revision = '2260b7ce0a62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sunsets', sa.Column('location', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sunsets', 'location')
    # ### end Alembic commands ###
