"""umami engaged

Revision ID: 99aac9513aa9
Revises: 99c487d4a887
Create Date: 2018-03-12 16:09:02.705993

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99aac9513aa9'
down_revision = '99c487d4a887'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meats', sa.Column('umaminess', sa.Text(), nullable=True))
    op.drop_column('meats', 'quality')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meats', sa.Column('quality', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('meats', 'umaminess')
    # ### end Alembic commands ###
