"""update beauty column to integer

Revision ID: 99cb63390322
Revises: 90d6930e06fd
Create Date: 2018-03-12 19:39:53.590440

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99cb63390322'
down_revision = '90d6930e06fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sunsets', 'beauty', type_=sa.Integer(),
                    postgresql_using='beauty::integer')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sunsets', 'beauty', type_=sa.Text(),
                    postgresql_using='beauty::text')
    # ### end Alembic commands ###
