"""url column prettiness to beaty

Revision ID: 9db8bcff1d34
Revises: 712bc7fe4cb7
Create Date: 2018-03-12 17:21:38.434240

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9db8bcff1d34'
down_revision = '712bc7fe4cb7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sunsets', sa.Column('beauty', sa.Text(), nullable=True))
    op.drop_column('sunsets', 'prettiness')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sunsets', sa.Column('prettiness', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('sunsets', 'beauty')
    # ### end Alembic commands ###
