"""adding not nullable to img_url column"

Revision ID: a2eeefb6c032
Revises: 036b7fa0b8bc
Create Date: 2018-03-12 15:39:55.036593

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2eeefb6c032'
down_revision = '036b7fa0b8bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pizza', 'img_url',
               existing_type=sa.Text(),
               nullable=False)
    op.alter_column('pizza', 'prettiness', existing_type=sa.Integer(), nullable=True, new_column_name='beauty')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pizza', 'img_url',
               existing_type=sa.Text(),
               nullable=True)
    op.alter_column('pizza', 'beauty', existing_type=sa.Integer(), nullable=True, new_column_name='prettiness')
    # ### end Alembic commands ###
