"""beauty column value type turned to integer

Revision ID: a3219ac59dee
Revises: d2ca282d6ec4
Create Date: 2018-03-12 17:05:37.971988

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3219ac59dee'
down_revision = 'd2ca282d6ec4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sunsets', 'beauty', type_=sa.Integer(), postgresql_using='beauty::integer')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sunsets', 'beauty', type_=sa.Text(), postgresql_using='beauty::text')
    # ### end Alembic commands ###
