"""we have made img url nullable=False

Revision ID: a9abb6d5b8e8
Revises: dfb20f93bcad
Create Date: 2018-03-12 18:39:48.278942

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9abb6d5b8e8'
down_revision = 'dfb20f93bcad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sunsets', 'img_url',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sunsets', 'img_url',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###
