"""changing datatype to integer for beauty

Revision ID: b14022a183bb
Revises: da31ebb504cb
Create Date: 2018-03-12 19:33:45.423355

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b14022a183bb'
down_revision = 'da31ebb504cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sunsets', 'beauty', type_=sa.Integer(), postgresql_using='beauty::integer')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sunsets', 'beauty', type_=sa.Text(), postgresql_using='beauty::text')
    # ### end Alembic commands ###
