"""adding a prettiness column

Revision ID: cac22ba52758
Revises: b660d20fc69b
Create Date: 2018-03-12 15:42:19.144723

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cac22ba52758'
down_revision = 'b660d20fc69b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sunsets', sa.Column('prettiness', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sunsets', 'prettiness')
    # ### end Alembic commands ###
