"""replaced prettiness with beauty

Revision ID: d2ca282d6ec4
Revises: 2408dbfa3f66
Create Date: 2018-03-12 16:38:22.474068

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2ca282d6ec4'
down_revision = '2408dbfa3f66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sunsets', 'prettiness', new_column_name = 'beauty')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sunsets', 'beauty', new_column_name = 'prettiness')
    # ### end Alembic commands ###
