"""added nullable to image_url

Revision ID: d8bcb41083c6
Revises: 0b17b7d75576
Create Date: 2018-03-12 16:22:31.229095

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8bcb41083c6'
down_revision = '0b17b7d75576'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sunsets', 'image_url',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sunsets', 'image_url',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###
