"""changing prettiness to beauty

Revision ID: da31ebb504cb
Revises: 49ff08e0e652
Create Date: 2018-03-12 19:16:11.394323

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da31ebb504cb'
down_revision = '49ff08e0e652'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('sunsets', sa.Column('beauty', sa.Text(), nullable=True))
    # op.drop_column('sunsets', 'prettiness')
    op.alter_column('sunsets', 'prettiness', new_column_name='beauty')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('sunsets', sa.Column('prettiness', sa.TEXT(), autoincrement=False, nullable=True))
    # op.drop_column('sunsets', 'beauty')
    op.alter_column('sunsets', 'beauty', new_column_name='prettiness')
    # ### end Alembic commands ###
