"""added location to Model

Revision ID: dfe77a347c75
Revises: fe0eae9d01de
Create Date: 2018-03-12 14:46:55.424190

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dfe77a347c75'
down_revision = 'fe0eae9d01de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sunsets', sa.Column('location', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sunsets', 'location')
    # ### end Alembic commands ###
