"""converted beauty column type to integer again

Revision ID: e0ec63ed5f84
Revises: 2bef4aba4df4
Create Date: 2018-03-12 17:05:42.929149

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0ec63ed5f84'
down_revision = '2bef4aba4df4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sunsets', 'beauty', type_=sa.Integer(), postgresql_using='beauty::integer')
    # type - what we want to change, postgres - how we will change it
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sunsets', 'beauty', type_=sa.Text(), postgresql_using='beauty::text')
    # ### end Alembic commands ###
