"""change name from prettiness to beauty

Revision ID: e855e0b420d6
Revises: 644add8be9bd
Create Date: 2018-03-12 18:52:31.227189

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e855e0b420d6'
down_revision = '644add8be9bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sunsets',"prettiness", new_column_name='beauty' )
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sunsets',"beauty", new_column_name='prettiness' )
    
    # ### end Alembic commands ###
