"""changed prettiness field-name to beauty

Revision ID: ea485e8459c6
Revises: 0789e3cd1cb9
Create Date: 2018-03-12 17:53:41.800042

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea485e8459c6'
down_revision = '0789e3cd1cb9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sunsets', sa.Column('beauty', sa.Text(), nullable=True))
    op.drop_column('sunsets', 'prettiness')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sunsets', sa.Column('prettiness', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('sunsets', 'beauty')
    # ### end Alembic commands ###
