"""nullable changed to false

Revision ID: fb525b712b86
Revises: cac22ba52758
Create Date: 2018-03-12 15:50:20.208492

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb525b712b86'
down_revision = 'cac22ba52758'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sunsets', 'img_url',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sunsets', 'img_url',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###
