"""change data type of beauty to integer

Revision ID: fc4c3eeb1e38
Revises: ea485e8459c6
Create Date: 2018-03-12 18:21:13.398901

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'fc4c3eeb1e38'
down_revision = 'ea485e8459c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'sunsets',
        'beauty',
        type_=sa.Integer(),
        postgresql_using='beauty::integer')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'sunsets', 'beauty', type_=sa.Text(), postgresql_using='beauty::text')
    # ### end Alembic commands ###
