"""adding password column for users

Revision ID: b071412378d4
Revises: db3e15b00bbe
Create Date: 2018-03-19 14:29:34.376685

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b071412378d4'
down_revision = 'db3e15b00bbe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('passsword', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'passsword')
    # ### end Alembic commands ###
