"""messagetag created

Revision ID: 550ff38fd9cc
Revises: ab8d08531717
Create Date: 2018-03-19 13:49:31.317734

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '550ff38fd9cc'
down_revision = 'ab8d08531717'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message_tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=True),
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('message_tag')
    # ### end Alembic commands ###
