"""edit column name

Revision ID: f79c8d891de4
Revises: d2f7426c3c8c
Create Date: 2018-03-13 19:20:00.920063

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f79c8d891de4'
down_revision = 'd2f7426c3c8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('user_id', sa.Integer(), nullable=True))
    op.drop_constraint('messages_user_fkey', 'messages', type_='foreignkey')
    op.create_foreign_key(None, 'messages', 'users', ['user_id'], ['id'])
    op.drop_column('messages', 'user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('user', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.create_foreign_key('messages_user_fkey', 'messages', 'users', ['user'], ['id'])
    op.drop_column('messages', 'user_id')
    # ### end Alembic commands ###
