"""adding img_url column

Revision ID: 146fe918cf34
Revises: 05fe03737915
Create Date: 2018-03-15 16:02:45.302076

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '146fe918cf34'
down_revision = '05fe03737915'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('img_url', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'img_url')
    # ### end Alembic commands ###
