"""create the messages table

Revision ID: 812c1c235fb6
Revises: 123408f4842a
Create Date: 2018-03-13 18:43:05.728389

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '812c1c235fb6'
down_revision = '123408f4842a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('messages')
    # ### end Alembic commands ###
