"""empty message

Revision ID: 328deb75ec97
Revises: 306150d83526
Create Date: 2018-03-15 08:49:43.987572

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '328deb75ec97'
down_revision = '306150d83526'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('image_url', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'image_url')
    # ### end Alembic commands ###
